# .github/workflows/pr-preview.yml
name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write
    steps:
      # Checkout the PR branch
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js for Astro
      - name: Setup Node.js
        if: github.event.action != 'closed'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Get package.json and package-lock.json from main if not in PR branch
      - name: Get package files from main if missing
        if: github.event.action != 'closed'
        run: |
          if [ ! -f "package.json" ]; then
            echo "No package.json in PR branch, fetching from main branch..."
            git fetch origin main --depth=1
            git show origin/main:package.json > package.json
            git show origin/main:package-lock.json > package-lock.json 2>/dev/null || echo "No package-lock.json"
            
            # Also get astro.config if missing
            if [ ! -f "astro.config.mjs" ]; then
              git show origin/main:astro.config.mjs > astro.config.mjs 2>/dev/null || echo "No astro.config.mjs"
            fi
          fi

      # Install dependencies
      - name: Install dependencies
        if: github.event.action != 'closed'
        run: npm ci || npm install

      # Build Astro site with base path for PR preview
      - name: Build Astro site
        if: github.event.action != 'closed'
        run: |
          # Build with the PR preview base path
          npm run build -- --base "/pr-preview/pr-${{ github.event.pull_request.number }}"
        env:
          PUBLIC_BASE_URL: "/pr-preview/pr-${{ github.event.pull_request.number }}"

      # Deploy the preview to GitHub Pages
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto

      # Post comment with preview URL
      - name: Get preview URL
        if: github.event.action != 'closed'
        id: preview-url
        run: |
          echo "url=https://serpdownloaders.github.io/pr-preview/pr-${{ github.event.pull_request.number }}/" >> $GITHUB_OUTPUT

      - name: Comment PR
        if: github.event.action != 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.preview-url.outputs.url }}';
            const body = `### 🚀 Deploy Preview ready!\n\n🔗 **Preview URL:** ${url}\n\n*This preview will be automatically updated when you push new commits to this PR.*`;
            
            // Find and update existing comment or create new one
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && comment.body.includes('Deploy Preview ready')
            );
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }
